import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import { AuthProvider } from '@/context/AuthContext';
import MainNavbar from '@/components/MainNavbar';
import ThemeApplier from '@/components/ThemeApplier';
import FooterBar from '@/components/FooterBar';

// Server-side: fetch settings and emit CSS variables so colors are present on initial render
async function getSettings() {
  try {
    const base = process.env.NEXT_PUBLIC_API_URL || 'http://127.0.0.1:5001/api';
    const res = await fetch(`${base}/settings`, { cache: 'no-store' });
    if (!res.ok) return null;
    return await res.json();
  } catch {
    return null;
  }
}

function hexToRgb(hexRaw: string | undefined) {
  if (!hexRaw) return null;
  const s = String(hexRaw).trim();
  if (s.startsWith('rgb')) {
    const m = s.match(/\(([^)]+)\)/);
    if (!m) return null;
    return m[1].split(/\s*,\s*/).slice(0,3).join(',');
  }
  let hex = s.replace('#','');
  if (hex.length === 3) hex = hex.split('').map(c => c + c).join('');
  if (hex.length !== 6) return null;
  const r = parseInt(hex.slice(0,2),16);
  const g = parseInt(hex.slice(2,4),16);
  const b = parseInt(hex.slice(4,6),16);
  if ([r,g,b].some(n => Number.isNaN(n))) return null;
  return `${r},${g},${b}`;
}

function readableForegroundFromRgbString(rgbStr: string | null) {
  if (!rgbStr) return '#ffffff';
  const parts = rgbStr.split(',').map(p => parseInt(p,10));
  if (parts.length < 3 || parts.some(isNaN)) return '#ffffff';
  const [r,g,b] = parts;
  const srgb = [r,g,b].map(v => v/255).map(v => v <= 0.03928 ? v/12.92 : Math.pow((v+0.055)/1.055, 2.4));
  const lum = 0.2126*srgb[0] + 0.7152*srgb[1] + 0.0722*srgb[2];
  return lum > 0.5 ? '#000000' : '#ffffff';
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/** Server-rendered theme CSS injected here so initial paint uses persisted colors */}
      <head />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased d-flex flex-column min-vh-100`}
      >
        <AuthProvider>
          {/* Server-side inject CSS vars */}
          {
             
          }
          <ServerTheme />
          <ThemeApplier />
          <MainNavbar />
          <main className="container py-4 grow">
            {children}
          </main>
          <FooterBar />
        </AuthProvider>
      </body>
    </html>
  );
}

// Server component that fetches settings and injects CSS variables
async function ServerTheme() {
  const settings = await getSettings();
  if (!settings) return null;
  const primary = settings.themePrimaryColor || '';
  const footer = settings.footerColor || '';
  const primaryRgb = hexToRgb(primary);
  const footerRgb = hexToRgb(footer);
  const footerFg = readableForegroundFromRgbString(footerRgb);

  const css = `:root { ${primary ? `--bs-primary: ${primary}; --brand-primary: ${primary};` : ''} ${primaryRgb ? `--bs-primary-rgb: ${primaryRgb}; --brand-primary-rgb: ${primaryRgb};` : ''} ${footer ? `--footer-bg: ${footer};` : ''} ${footerFg ? `--footer-foreground: ${footerFg};` : ''} }`;

  return (
     
    <style dangerouslySetInnerHTML={{ __html: css }} />
  );
}
